version: "3.9"

services:
  exam-db:
    container_name: exam-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      # external:internal
      - "5439:5432"
    volumes:
      - exam-db-postgres-volume:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      main:
        aliases:
          - exam-db

volumes:
  exam-db-postgres-volume:

networks:
  main: